# Generated by Django 3.2.16 on 2023-01-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='detail_text',
            field=models.TextField(default='This is description', max_length=500),
        ),
    ]
